FROM node:14.8.0-alpine

WORKDIR /bot

COPY . /bot
# COPY package.json package.json
# COPY yarn.lock yarn.lock
# RUN rm config.js

RUN mkdir -p log/error
RUN chown -R node:node log
# RUN rm /app/src/Config/*

RUN yarn install
RUN echo "Asia/Shanghai" > /etc/timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV PATH=$PATH:/home/node/.npm-global/bin

CMD ["node","bot.js"]

# EXPOSE 3001/tcp
USER node
